# Generated by Django 5.2.4 on 2025-07-17 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0002_cliente_fornecedor_grupopeca_alter_peca_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='kilometragem',
            field=models.IntegerField(default=1000, help_text='Quilometragem do veículo no momento do serviço.', verbose_name='Quilometragem'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='FotoServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='fotos_servicos/')),
                ('descricao', models.CharField(blank=True, max_length=255, null=True)),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='loja.servico')),
            ],
        ),
    ]
